force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drinks</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Main dishes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beer</fullName>
            </value>
            <value>
                <fullName>Bread</fullName>
            </value>
            <value>
                <fullName>Biscuits</fullName>
            </value>
            <value>
                <fullName>Muffins</fullName>
            </value>
            <value>
                <fullName>Vegetable garnish</fullName>
            </value>
            <value>
                <fullName>Cereal garnish</fullName>
            </value>
            <value>
                <fullName>Fried dishes</fullName>
            </value>
            <value>
                <fullName>Stews dishes</fullName>
            </value>
            <value>
                <fullName>Baked dishes</fullName>
            </value>
            <value>
                <fullName>Sandwiches</fullName>
            </value>
            <value>
                <fullName>Paste</fullName>
            </value>
            <value>
                <fullName>Caviar</fullName>
            </value>
            <value>
                <fullName>Sneeks</fullName>
            </value>
            <value>
                <fullName>Canape</fullName>
            </value>
            <value>
                <fullName>Tartlets</fullName>
            </value>
            <value>
                <fullName>Threads</fullName>
            </value>
            <value>
                <fullName>Pickles</fullName>
            </value>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Chicken</fullName>
            </value>
            <value>
                <fullName>Pork</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Fried</fullName>
            </value>
            <value>
                <fullName>Boiled</fullName>
            </value>
            <value>
                <fullName>Stewed</fullName>
            </value>
            <value>
                <fullName>River fish</fullName>
            </value>
            <value>
                <fullName>Sea fish</fullName>
            </value>
            <value>
                <fullName>Seafood</fullName>
            </value>
            <value>
                <fullName>Vegetable</fullName>
            </value>
            <value>
                <fullName>Meaty</fullName>
            </value>
            <value>
                <fullName>Lungs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DishControllerTest.cls
//Class for testing DishController class
@isTest
public with sharing class DishControllerTest {

    public static String TEST_DISH_NAME = 'Garag limon';
    public static String TEST_DISH_CATEGORY = 'Drinks';
    public static String TEST_DISH_SUBCATEGORY = 'Beer';

    public static String EXPECTED_NO_DISHES = 'Actual amount of dishes does not equal to excpected.';
    public static String INVALID_AMOUNT = 'Actual amount of dishes does not equal to excpected.';

    @isTest
    public static void testEmptyDishes() {
        List<Dish__c> dishes = DishController.getListOfDishes();
        System.assertEquals(0, dishes.size(), EXPECTED_NO_DISHES);
    }

    @isTest
    public static void testWithDishData() {
        List<Dish__c> dishes = new List<Dish__c>();
        Integer length = 3;

        for(Integer i = 0; i < length; i++) {
            Dish__c dish = new Dish__c(Title__c = TEST_DISH_NAME,
                                       Category__c = TEST_DISH_CATEGORY,
                                       Subcategory__c = TEST_DISH_SUBCATEGORY,
                                       Price__c = i);
            dishes.add(dish);
        }
        insert dishes;

        List<Dish__c> resultDishes = DishController.getListOfDishes();
        System.assertEquals(length, resultDishes.size(), INVALID_AMOUNT); 
    }

}