force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Restaurant_Order__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Order__c</fullName>
    <label>Restaurant Order</label>
    <referenceTo>Restaurant_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant_Order__c/Restaurant_Order__c.object-meta.xml
<CustomObject>
    <label>Restaurant Order</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restaurant Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Order__c/fields/IsDelivery__c.field-meta.xml
<CustomField>
    <fullName>IsDelivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDelivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Restaurant_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant_Order__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RestaurantOrderController.cls
public with sharing class RestaurantOrderController {

    @AuraEnabled
    public static Restaurant_Order__c getOrder() {
        Id userId = UserInfo.getUserId();
        Restaurant_Order__c order = [SELECT Name, OwnerId, Status__c FROM Restaurant_Order__c 
                                    WHERE OwnerId = :userId AND Status__c = 'Open' LIMIT 1];
        return order;
    }

    @AuraEnabled
    public static void checkOrderExistence(){
        Id userId = UserInfo.getUserId();
        Restaurant_Order__c order;

        try {
            order = [SELECT Name, OwnerId, Status__c FROM Restaurant_Order__c 
                    WHERE OwnerId = :userId AND Status__c = 'Open' LIMIT 1];
        } catch (System.QueryException queryException) {
            order = new Restaurant_Order__c();
            insert order;
        }
    }

    @AuraEnabled
    public static List<Restaurant_Order__c> getPreviousOrders(){
        Id userId = UserInfo.getUserId();
        List<Restaurant_Order__c> orders = [SELECT Name, OwnerId,	IsDelivery__c, Delivery_Address__c, 
                            Order_Date__c, Status__c, Sum__c, (SELECT Dish__r.Title__c FROM Order_Items__r)
                            FROM Restaurant_Order__c WHERE OwnerId = :userId AND Status__c = 'Closed'];
        
        return orders;
    }
   
}