force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drinks</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Main dishes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beer</fullName>
            </value>
            <value>
                <fullName>Bread</fullName>
            </value>
            <value>
                <fullName>Biscuits</fullName>
            </value>
            <value>
                <fullName>Muffins</fullName>
            </value>
            <value>
                <fullName>Vegetable garnish</fullName>
            </value>
            <value>
                <fullName>Cereal garnish</fullName>
            </value>
            <value>
                <fullName>Fried dishes</fullName>
            </value>
            <value>
                <fullName>Stews dishes</fullName>
            </value>
            <value>
                <fullName>Baked dishes</fullName>
            </value>
            <value>
                <fullName>Sandwiches</fullName>
            </value>
            <value>
                <fullName>Paste</fullName>
            </value>
            <value>
                <fullName>Caviar</fullName>
            </value>
            <value>
                <fullName>Sneeks</fullName>
            </value>
            <value>
                <fullName>Canape</fullName>
            </value>
            <value>
                <fullName>Tartlets</fullName>
            </value>
            <value>
                <fullName>Threads</fullName>
            </value>
            <value>
                <fullName>Pickles</fullName>
            </value>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Chicken</fullName>
            </value>
            <value>
                <fullName>Pork</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Fried</fullName>
            </value>
            <value>
                <fullName>Boiled</fullName>
            </value>
            <value>
                <fullName>Stewed</fullName>
            </value>
            <value>
                <fullName>River fish</fullName>
            </value>
            <value>
                <fullName>Sea fish</fullName>
            </value>
            <value>
                <fullName>Seafood</fullName>
            </value>
            <value>
                <fullName>Vegetable</fullName>
            </value>
            <value>
                <fullName>Meaty</fullName>
            </value>
            <value>
                <fullName>Lungs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Restaurant_Order__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Order__c</fullName>
    <label>Restaurant Order</label>
    <referenceTo>Restaurant_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant_Order__c/Restaurant_Order__c.object-meta.xml
<CustomObject>
    <label>Restaurant Order</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restaurant Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderItemControllerTest.cls
//Class for testing OrderItemController class
@isTest
public with sharing class OrderItemControllerTest {

    public static String OPEN_STATUS = 'Open';

    public static String TEST_DISH_NAME = 'Garag limon';
    public static String TEST_DISH_CATEGORY = 'Drinks';
    public static String TEST_DISH_SUBCATEGORY = 'Beer';
    public static Decimal TEST_PRICE = 1.0;

    public static String EXPECTED_NO_ITEMS = 'Actual amount of order items does not equal to excpected.';
    public static String INVALID_AMOUNT = 'Actual amount of order items does not equal to excpected.';
    public static String INVALID_ID = 'Actual id of order items does not equal to excpected.';

    @TestSetup
    static void makeData(){
        Restaurant_Order__c order = new Restaurant_Order__c(Status__c = OPEN_STATUS);
        insert order;

        Dish__c dish = new Dish__c( Title__c = TEST_DISH_NAME,
                                    Category__c = TEST_DISH_CATEGORY,
                                    Subcategory__c = TEST_DISH_SUBCATEGORY,
                                    Price__c = TEST_PRICE);
        insert dish;
    }

    @IsTest
    public static void getOrderItemsByOrderIdEmpty() {
        Restaurant_Order__c order = [SELECT Name FROM Restaurant_Order__c WHERE Status__c = 'Open' LIMIT 1];
        List<Order_Item__c> items;

        try {
            items = OrderItemController.getOrderItemsByOrderId(order.Id);
        } catch (System.QueryException queryException) {
            System.assertEquals(queryException.getMessage(), queryException.getMessage());
        }

        System.assertEquals(0, items.size(), EXPECTED_NO_ITEMS);
    }

    @IsTest
    public static void getOrderItemsByOrderId() {
        Restaurant_Order__c order = [SELECT Name FROM Restaurant_Order__c WHERE Status__c = 'Open' LIMIT 1];
        Dish__c dish = [SELECT Name FROM Dish__c LIMIT 1];

        Integer length = 3;
        List<Order_Item__c> items = new List<Order_Item__c>();

        for(Integer i = 0; i < length; i++) {
            Order_Item__c orderItem = new Order_Item__c(Dish__c = dish.Id,
                                                        Amount__c = 1,
                                                        Restaurant_Order__c = order.Id);
            items.add(orderItem);
        }
        insert items;

        List<Order_Item__c> resultItems = OrderItemController.getOrderItemsByOrderId(order.Id);
        System.assertEquals(length, resultItems.size(), EXPECTED_NO_ITEMS);
    }

    @IsTest
    public static void getOrderItemByIdTest() {
        Restaurant_Order__c order = [SELECT Name FROM Restaurant_Order__c WHERE Status__c = 'Open' LIMIT 1];
        Dish__c dish = [SELECT Name FROM Dish__c LIMIT 1];

        Order_Item__c orderItem = new Order_Item__c(Dish__c = dish.Id,
                                                    Amount__c = 1,
                                                    Restaurant_Order__c = order.Id);
        insert orderItem;

        Order_Item__c resultOrderItem = OrderItemController.getOrderItemById(orderItem.Id);
        System.assertEquals(orderItem.Id, resultOrderItem.Id, INVALID_ID);
    }

}